const STORAGE_KEY="notion-habit-tracker-v4";
const defaultAppearance={background:"#f7f4f5",surface:"#ffffff",text:"#4a4547",muted:"#888083",border:"#e5dfe1",accent:"#d9a8b5",completed:"#d9a8b5",radius:18,cellRadius:10,bodyFontSize:14,titleFontSize:20,gap:8,titleFont:"IM Fell DW Pica",bodyFont:"IM Fell DW Pica",titleFontStyle:"italic",bodyFontStyle:"normal"};
const defaultState={settings:{title:"DIÁRIO 🔥",habits:[{id:"habit-1",name:"arrumar quarto"},{id:"habit-2",name:"aspirar a casa"},{id:"habit-3",name:"escovar dentes"},{id:"habit-4",name:"lavar louça"},{id:"habit-5",name:"limpar areia"},{id:"habit-6",name:"responder WhatsApp"},{id:"habit-7",name:"checar SLP"}],appearance:defaultAppearance},weeks:{}};
let state=loadState(),currentWeekStart=getMonday(new Date()),fontCatalog=[],fontOffsets={title:0,body:0},fontSearchTimers={},activeColorKey=null,pickerHSV={h:0,s:0,v:100};

function loadState(){try{let s=JSON.parse(localStorage.getItem(STORAGE_KEY))||JSON.parse(localStorage.getItem("notion-habit-tracker-v3"))||JSON.parse(localStorage.getItem("notion-habit-tracker-v2"))||JSON.parse(localStorage.getItem("notion-habit-tracker-v1"));let old=s?.settings?.appearance||{};if(old.font){old.titleFont??=old.font;old.bodyFont??=old.font;old.titleFontStyle??=old.fontStyle||"normal";old.bodyFontStyle??=old.fontStyle||"normal"}if(old.fontSize){old.bodyFontSize??=old.fontSize;old.titleFontSize??=20}return s?{settings:{...defaultState.settings,...s.settings,appearance:{...defaultAppearance,...old}},weeks:s.weeks||{}}:structuredClone(defaultState)}catch{return structuredClone(defaultState)}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function googleFontURL(name){return `https://fonts.googleapis.com/css2?family=${encodeURIComponent(name).replace(/%20/g,"+")}:ital,wght@0,400;1,400&display=swap`}
function loadGoogleFont(name,target){document.getElementById(target+"GoogleFont").href=googleFontURL(name)}
function applyAppearance(){const a=state.settings.appearance,r=document.documentElement;loadGoogleFont(a.titleFont,"title");loadGoogleFont(a.bodyFont,"body");Object.entries({background:a.background,surface:a.surface,text:a.text,muted:a.muted,border:a.border,accent:a.accent,completed:a.completed}).forEach(([k,v])=>r.style.setProperty("--"+k,v));r.style.setProperty("--radius",a.radius+"px");r.style.setProperty("--cell-radius",a.cellRadius+"px");r.style.setProperty("--body-font-size",a.bodyFontSize+"px");r.style.setProperty("--title-font-size",a.titleFontSize+"px");r.style.setProperty("--gap",a.gap+"px");r.style.setProperty("--title-font",`"${a.titleFont}", serif`);r.style.setProperty("--body-font",`"${a.bodyFont}", sans-serif`);r.style.setProperty("--title-font-style",a.titleFontStyle);r.style.setProperty("--body-font-style",a.bodyFontStyle)}
function toISODate(d){let x=new Date(d);x.setHours(12,0,0,0);return x.toISOString().slice(0,10)}function getMonday(d){let x=new Date(d);x.setHours(12,0,0,0);let day=x.getDay();x.setDate(x.getDate()+(day===0?-6:1-day));return x}function addDays(d,n){let x=new Date(d);x.setDate(x.getDate()+n);return x}function getWeekKey(){return toISODate(currentWeekStart)}
function formatRange(s){let e=addDays(s,6),a={day:"numeric",month:"short"},b={day:"numeric",month:"short",year:"numeric"};return `${s.toLocaleDateString("pt-BR",a)} – ${e.toLocaleDateString("pt-BR",b)}`}
function getWeekData(){let k=getWeekKey();if(!state.weeks[k])state.weeks[k]={};return state.weeks[k]}function isFuture(d){let t=new Date();t.setHours(0,0,0,0);let x=new Date(d);x.setHours(0,0,0,0);return x>t}
function render(){applyAppearance();widgetTitle.textContent=state.settings.title;dateRange.textContent=formatRange(currentWeekStart);daysHeader.innerHTML="";habitsGrid.innerHTML="";["SEG","TER","QUA","QUI","SEX","SÁB","DOM"].forEach((n,i)=>{let d=addDays(currentWeekStart,i),el=document.createElement("div");el.className="day-header";el.innerHTML=`<span class="day-name">${n}</span><span class="day-number">${d.getDate()}</span>`;daysHeader.appendChild(el)});let wd=getWeekData();state.settings.habits.forEach(h=>{let row=document.createElement("div");row.className="habit-row";let name=document.createElement("div");name.className="habit-name";name.textContent=h.name;let checks=document.createElement("div");checks.className="checks";for(let i=0;i<7;i++){let d=addDays(currentWeekStart,i),key=toISODate(d),b=document.createElement("button");b.className="check";if(wd?.[h.id]?.[key])b.classList.add("completed");if(isFuture(d))b.disabled=true;b.onclick=()=>{let data=getWeekData();if(!data[h.id])data[h.id]={};data[h.id][key]=!data[h.id][key];saveState();render()};checks.appendChild(b)}row.append(name,checks);habitsGrid.appendChild(row)});saveState()}
prevWeek.onclick=()=>{currentWeekStart=addDays(currentWeekStart,-7);render()};nextWeek.onclick=()=>{currentWeekStart=addDays(currentWeekStart,7);render()};todayWeek.onclick=()=>{currentWeekStart=getMonday(new Date());render()};
settingsButton.onclick=()=>{renderSettings();settingsDialog.showModal()};closeSettings.onclick=()=>settingsDialog.close();
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".tab-content").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.getElementById(b.dataset.tab+"Tab").classList.add("active")});

const colorLabels={background:"Fundo do widget",surface:"Fundo das caixas",text:"Texto principal",muted:"Texto secundário",border:"Bordas",accent:"Cor de destaque",completed:"Marcação concluída"};
const colorFields=Object.keys(colorLabels);
function renderColorControls(){colorControls.innerHTML="";colorFields.forEach(k=>{let b=document.createElement("button");b.type="button";b.className="color-button";b.innerHTML=`<span class="color-swatch" style="background:${state.settings.appearance[k]}"></span><span>${colorLabels[k]}</span>`;b.onclick=()=>openColorPicker(k);colorControls.appendChild(b)})}
function renderSettings(){let a=state.settings.appearance;titleInput.value=state.settings.title;renderColorControls();titleFontSearch.value=a.titleFont;bodyFontSearch.value=a.bodyFont;titleFontName.textContent=a.titleFont;bodyFontName.textContent=a.bodyFont;titleFontPreview.style.fontFamily=`"${a.titleFont}", serif`;titleFontPreview.style.fontStyle=a.titleFontStyle;bodyFontPreview.style.fontFamily=`"${a.bodyFont}", sans-serif`;bodyFontPreview.style.fontStyle=a.bodyFontStyle;titleFontStyleInput.value=a.titleFontStyle;bodyFontStyleInput.value=a.bodyFontStyle;["titleFontSize","bodyFontSize","radius","cellRadius","gap"].forEach(k=>{let i=document.getElementById(k+"Input");i.value=a[k];document.getElementById(k+"Value").textContent=a[k]+"px"});renderHabitEditor()}
function renderHabitEditor(){habitEditor.innerHTML="";state.settings.habits.forEach((h,i)=>{let r=document.createElement("div");r.className="editor-row";let input=document.createElement("input");input.value=h.name;input.dataset.id=h.id;let up=document.createElement("button");up.textContent="↑";up.disabled=i===0;up.onclick=()=>{[state.settings.habits[i-1],state.settings.habits[i]]=[state.settings.habits[i],state.settings.habits[i-1]];renderHabitEditor()};let down=document.createElement("button");down.textContent="↓";down.disabled=i===state.settings.habits.length-1;down.onclick=()=>{[state.settings.habits[i+1],state.settings.habits[i]]=[state.settings.habits[i],state.settings.habits[i+1]];renderHabitEditor()};let del=document.createElement("button");del.textContent="×";del.onclick=()=>{state.settings.habits.splice(i,1);renderHabitEditor()};r.append(input,up,down,del);habitEditor.appendChild(r)})}
["titleFontSize","bodyFontSize","radius","cellRadius","gap"].forEach(k=>document.getElementById(k+"Input").oninput=e=>document.getElementById(k+"Value").textContent=e.target.value+"px");
addHabit.onclick=()=>{state.settings.habits.push({id:"habit-"+Date.now(),name:"novo hábito"});renderHabitEditor()};

async function fetchFontCatalog(){if(fontCatalog.length)return fontCatalog;try{let r=await fetch("https://fonts.google.com/metadata/fonts");let text=(await r.text()).replace(/^\)\]\}'\s*/,"");let data=JSON.parse(text);fontCatalog=(data.familyMetadataList||[]).map(x=>({family:x.family,category:x.category||""})).sort((a,b)=>a.family.localeCompare(b.family));}catch(e){fontCatalog=["IM Fell DW Pica","Cormorant Garamond","Playfair Display","DM Sans","Inter","Manrope","EB Garamond","Libre Baskerville","Caveat","Special Elite","Space Grotesk","Bodoni Moda","Fraunces","Lora","Montserrat","Poppins","Nunito","Oswald","Roboto Slab","Archivo","Bitter","Karla"].map(f=>({family:f,category:""}))}return fontCatalog}
async function renderFontResults(target,reset=false){let input=document.getElementById(target+"FontSearch"),resultsEl=document.getElementById(target+"FontResults");if(reset){fontOffsets[target]=0;resultsEl.innerHTML=""}let catalog=await fetchFontCatalog(),q=input.value.trim().toLowerCase();let filtered=q?catalog.filter(x=>x.family.toLowerCase().includes(q)):catalog;let start=fontOffsets[target],batch=filtered.slice(start,start+20);if(!batch.length&&start===0){resultsEl.innerHTML="<div style='padding:12px;font-size:12px'>Nenhuma fonte encontrada.</div>";return}batch.forEach(item=>{loadGoogleFont(item.family,target);let b=document.createElement("button");b.type="button";b.className="font-result";b.style.fontFamily=`"${item.family}", serif`;b.innerHTML=`${item.family}<small>${item.category}</small>`;b.onclick=()=>selectFont(item.family,target);resultsEl.appendChild(b)});fontOffsets[target]+=batch.length;document.getElementById("loadMore"+(target==="title"?"Title":"Body")+"Fonts").style.display=fontOffsets[target]>=filtered.length?"none":"block"}
function selectFont(name,target){state.settings.appearance[target+"Font"]=name;loadGoogleFont(name,target);document.getElementById(target+"FontSearch").value=name;document.getElementById(target+"FontName").textContent=name;let preview=document.getElementById(target+"FontPreview");preview.style.fontFamily=`"${name}", serif`;document.getElementById(target+"FontResults").innerHTML=""}
function setupFontBrowser(target){let search=document.getElementById(target+"FontSearch"),browse=document.getElementById("browse"+(target==="title"?"Title":"Body")+"Fonts"),more=document.getElementById("loadMore"+(target==="title"?"Title":"Body")+"Fonts");browse.onclick=()=>renderFontResults(target,true);more.onclick=()=>renderFontResults(target,false);search.oninput=()=>{clearTimeout(fontSearchTimers[target]);fontSearchTimers[target]=setTimeout(()=>renderFontResults(target,true),200)}}
setupFontBrowser("title");setupFontBrowser("body");

saveSettings.onclick=()=>{state.settings.title=titleInput.value.trim()||"DIÁRIO";habitEditor.querySelectorAll("input[data-id]").forEach(i=>{let h=state.settings.habits.find(x=>x.id===i.dataset.id);if(h)h.name=i.value.trim()||"Novo hábito"});let a=state.settings.appearance;a.titleFontStyle=titleFontStyleInput.value;a.bodyFontStyle=bodyFontStyleInput.value;["titleFontSize","bodyFontSize","radius","cellRadius","gap"].forEach(k=>a[k]=Number(document.getElementById(k+"Input").value));saveState();settingsDialog.close();render()};
resetAppearance.onclick=()=>{state.settings.appearance={...defaultAppearance};renderSettings();applyAppearance()};resetCurrentWeek.onclick=()=>{if(confirm("Deseja apagar todas as marcações desta semana?")){delete state.weeks[getWeekKey()];saveState();settingsDialog.close();render()}};
titleFontStyleInput.onchange=()=>titleFontPreview.style.fontStyle=titleFontStyleInput.value;bodyFontStyleInput.onchange=()=>bodyFontPreview.style.fontStyle=bodyFontStyleInput.value;

/* Color picker */
function hexToRgb(hex){hex=hex.replace("#","");if(hex.length===3)hex=hex.split("").map(x=>x+x).join("");let n=parseInt(hex,16);return{r:(n>>16)&255,g:(n>>8)&255,b:n&255}}function rgbToHex(r,g,b){return "#"+[r,g,b].map(x=>Math.max(0,Math.min(255,Math.round(x))).toString(16).padStart(2,"0")).join("")}
function rgbToHsv(r,g,b){r/=255;g/=255;b/=255;let max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min,h=0;if(d){if(max===r)h=60*(((g-b)/d)%6);else if(max===g)h=60*((b-r)/d+2);else h=60*((r-g)/d+4)}if(h<0)h+=360;return{h:Math.round(h),s:Math.round(max?d/max*100:0),v:Math.round(max*100)}}
function hsvToRgb(h,s,v){s/=100;v/=100;let c=v*s,x=c*(1-Math.abs((h/60)%2-1)),m=v-c,r=0,g=0,b=0;if(h<60)[r,g,b]=[c,x,0];else if(h<120)[r,g,b]=[x,c,0];else if(h<180)[r,g,b]=[0,c,x];else if(h<240)[r,g,b]=[0,x,c];else if(h<300)[r,g,b]=[x,0,c];else[r,g,b]=[c,0,x];return{r:Math.round((r+m)*255),g:Math.round((g+m)*255),b:Math.round((b+m)*255)}}function hsvHex(){let{r,g,b}=hsvToRgb(pickerHSV.h,pickerHSV.s,pickerHSV.v);return rgbToHex(r,g,b)}
function updatePicker(){let hue=`hsl(${pickerHSV.h},100%,50%)`;colorSquare.style.background=`linear-gradient(to top,#000,transparent),linear-gradient(to right,#fff,${hue})`;colorSquareCursor.style.left=pickerHSV.s+"%";colorSquareCursor.style.top=(100-pickerHSV.v)+"%";let rgb=hsvToRgb(pickerHSV.h,pickerHSV.s,pickerHSV.v),hex=rgbToHex(rgb.r,rgb.g,rgb.b);colorPreview.style.background=hex;hInput.value=pickerHSV.h;sInput.value=pickerHSV.s;bInput.value=pickerHSV.v;rInput.value=rgb.r;gInput.value=rgb.g;bRgbInput.value=rgb.b;hexInput.value=hex}
function openColorPicker(key){activeColorKey=key;colorDialogTitle.textContent=`Escolher cor: ${colorLabels[key]}`;let rgb=hexToRgb(state.settings.appearance[key]);pickerHSV=rgbToHsv(rgb.r,rgb.g,rgb.b);hueSlider.value=pickerHSV.h;updatePicker();colorDialog.showModal()}
function squarePosition(e){let rect=colorSquare.getBoundingClientRect(),x=Math.max(0,Math.min(rect.width,e.clientX-rect.left)),y=Math.max(0,Math.min(rect.height,e.clientY-rect.top));pickerHSV.s=Math.round(x/rect.width*100);pickerHSV.v=Math.round(100-y/rect.height*100);updatePicker()}
colorSquare.addEventListener("pointerdown",e=>{colorSquare.setPointerCapture(e.pointerId);squarePosition(e)});colorSquare.addEventListener("pointermove",e=>{if(e.buttons)squarePosition(e)});hueSlider.oninput=e=>{pickerHSV.h=Number(e.target.value);updatePicker()};
[hInput,sInput,bInput].forEach(el=>el.oninput=()=>{pickerHSV.h=Math.max(0,Math.min(360,Number(hInput.value)||0));pickerHSV.s=Math.max(0,Math.min(100,Number(sInput.value)||0));pickerHSV.v=Math.max(0,Math.min(100,Number(bInput.value)||0));hueSlider.value=pickerHSV.h;updatePicker()});
[rInput,gInput,bRgbInput].forEach(el=>el.oninput=()=>{pickerHSV=rgbToHsv(Number(rInput.value)||0,Number(gInput.value)||0,Number(bRgbInput.value)||0);hueSlider.value=pickerHSV.h;updatePicker()});hexInput.oninput=()=>{if(/^#?[0-9a-fA-F]{6}$/.test(hexInput.value)){let rgb=hexToRgb(hexInput.value);pickerHSV=rgbToHsv(rgb.r,rgb.g,rgb.b);hueSlider.value=pickerHSV.h;updatePicker()}};
closeColorPicker.onclick=()=>colorDialog.close();cancelColor.onclick=()=>colorDialog.close();applyColor.onclick=()=>{if(activeColorKey){state.settings.appearance[activeColorKey]=hsvHex();renderColorControls();colorDialog.close()}};
render();