const STORAGE_KEY="notion-habit-tracker-v3";
const defaultAppearance={background:"#f7f4f5",surface:"#ffffff",text:"#4a4547",muted:"#888083",border:"#e5dfe1",accent:"#d9a8b5",completed:"#d9a8b5",radius:18,cellRadius:10,fontSize:14,gap:8,font:"IM Fell DW Pica",fontStyle:"italic"};
const defaultState={settings:{title:"DAILY 🔥",habits:[{id:"habit-1",name:"arrumar quarto"},{id:"habit-2",name:"aspirar a casa"},{id:"habit-3",name:"escovar dentes"},{id:"habit-4",name:"lavar louça"},{id:"habit-5",name:"limpar areia"},{id:"habit-6",name:"responder wpp"},{id:"habit-7",name:"checar SLP"}],appearance:defaultAppearance},weeks:{}};
let state=loadState(),currentWeekStart=getMonday(new Date()),fontCatalog=[],fontSearchTimer=null,activeColorKey=null,pickerHSV={h:0,s:0,v:100};

function loadState(){try{let s=JSON.parse(localStorage.getItem(STORAGE_KEY))||JSON.parse(localStorage.getItem("notion-habit-tracker-v2"))||JSON.parse(localStorage.getItem("notion-habit-tracker-v1"));return s?{settings:{...defaultState.settings,...s.settings,appearance:{...defaultAppearance,...(s.settings?.appearance||{})}},weeks:s.weeks||{}}:structuredClone(defaultState)}catch{return structuredClone(defaultState)}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function loadGoogleFont(name){let family=name.trim().replace(/\s+/g,"+");document.getElementById("dynamicGoogleFont").href=`https://fonts.googleapis.com/css2?family=${family}:ital,wght@0,400;1,400&display=swap`}
function applyAppearance(){const a=state.settings.appearance,r=document.documentElement;loadGoogleFont(a.font);Object.entries({background:a.background,surface:a.surface,text:a.text,muted:a.muted,border:a.border,accent:a.accent,completed:a.completed}).forEach(([k,v])=>r.style.setProperty("--"+k,v));r.style.setProperty("--radius",a.radius+"px");r.style.setProperty("--cell-radius",a.cellRadius+"px");r.style.setProperty("--font-size",a.fontSize+"px");r.style.setProperty("--gap",a.gap+"px");r.style.setProperty("--font-family",`"${a.font}", serif`);r.style.setProperty("--font-style",a.fontStyle)}
function toISODate(d){let x=new Date(d);x.setHours(12,0,0,0);return x.toISOString().slice(0,10)}function getMonday(d){let x=new Date(d);x.setHours(12,0,0,0);let day=x.getDay();x.setDate(x.getDate()+(day===0?-6:1-day));return x}function addDays(d,n){let x=new Date(d);x.setDate(x.getDate()+n);return x}function getWeekKey(){return toISODate(currentWeekStart)}
function formatRange(s){let e=addDays(s,6),same=s.getMonth()===e.getMonth(),a={month:"short",day:"numeric"},b=same?{day:"numeric",year:"numeric"}:{month:"short",day:"numeric",year:"numeric"};return `${s.toLocaleDateString("en-US",a)} – ${e.toLocaleDateString("en-US",b)}`}
function getWeekData(){let k=getWeekKey();if(!state.weeks[k])state.weeks[k]={};return state.weeks[k]}function isFuture(d){let t=new Date();t.setHours(0,0,0,0);let x=new Date(d);x.setHours(0,0,0,0);return x>t}
function render(){applyAppearance();widgetTitle.textContent=state.settings.title;dateRange.textContent=formatRange(currentWeekStart);daysHeader.innerHTML="";habitsGrid.innerHTML="";["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].forEach((n,i)=>{let d=addDays(currentWeekStart,i),el=document.createElement("div");el.className="day-header";el.innerHTML=`<span class="day-name">${n}</span><span class="day-number">${d.getDate()}</span>`;daysHeader.appendChild(el)});let wd=getWeekData();state.settings.habits.forEach(h=>{let row=document.createElement("div");row.className="habit-row";let name=document.createElement("div");name.className="habit-name";name.textContent=h.name;let checks=document.createElement("div");checks.className="checks";for(let i=0;i<7;i++){let d=addDays(currentWeekStart,i),key=toISODate(d),b=document.createElement("button");b.className="check";if(wd?.[h.id]?.[key])b.classList.add("completed");if(isFuture(d))b.disabled=true;b.onclick=()=>{let data=getWeekData();if(!data[h.id])data[h.id]={};data[h.id][key]=!data[h.id][key];saveState();render()};checks.appendChild(b)}row.append(name,checks);habitsGrid.appendChild(row)});saveState()}
prevWeek.onclick=()=>{currentWeekStart=addDays(currentWeekStart,-7);render()};nextWeek.onclick=()=>{currentWeekStart=addDays(currentWeekStart,7);render()};todayWeek.onclick=()=>{currentWeekStart=getMonday(new Date());render()};

const dialog=settingsDialog;settingsButton.onclick=()=>{renderSettings();dialog.showModal()};closeSettings.onclick=()=>dialog.close();
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".tab-content").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.getElementById(b.dataset.tab+"Tab").classList.add("active")});

const colorFields=["background","surface","text","muted","border","accent","completed"];
function renderColorControls(){colorControls.innerHTML="";colorFields.forEach(k=>{let b=document.createElement("button");b.type="button";b.className="color-button";let label=k.replace(/([A-Z])/g," $1").replace(/^./,x=>x.toUpperCase());b.innerHTML=`<span class="color-swatch" style="background:${state.settings.appearance[k]}"></span><span>${label}</span>`;b.onclick=()=>openColorPicker(k);colorControls.appendChild(b)})}
function renderSettings(){titleInput.value=state.settings.title;renderColorControls();fontSearch.value=state.settings.appearance.font;fontPreview.textContent="The quick brown fox jumps over the lazy dog.";fontPreview.style.fontFamily=`"${state.settings.appearance.font}", serif`;fontPreview.style.fontStyle=state.settings.appearance.fontStyle;fontStyleInput.value=state.settings.appearance.fontStyle;["fontSize","radius","cellRadius","gap"].forEach(k=>{let i=document.getElementById(k+"Input");i.value=state.settings.appearance[k];document.getElementById(k+"Value").textContent=state.settings.appearance[k]+"px"});habitEditor.innerHTML="";state.settings.habits.forEach((h,i)=>{let r=document.createElement("div");r.className="editor-row";let input=document.createElement("input");input.value=h.name;input.dataset.id=h.id;let up=document.createElement("button");up.textContent="↑";up.disabled=i===0;up.onclick=()=>{[state.settings.habits[i-1],state.settings.habits[i]]=[state.settings.habits[i],state.settings.habits[i-1]];renderSettings()};let down=document.createElement("button");down.textContent="↓";down.disabled=i===state.settings.habits.length-1;down.onclick=()=>{[state.settings.habits[i+1],state.settings.habits[i]]=[state.settings.habits[i],state.settings.habits[i+1]];renderSettings()};let del=document.createElement("button");del.textContent="×";del.onclick=()=>{state.settings.habits.splice(i,1);renderSettings()};r.append(input,up,down,del);habitEditor.appendChild(r)})}
["fontSize","radius","cellRadius","gap"].forEach(k=>document.getElementById(k+"Input").oninput=e=>document.getElementById(k+"Value").textContent=e.target.value+"px");
addHabit.onclick=()=>{state.settings.habits.push({id:"habit-"+Date.now(),name:"new habit"});renderSettings()};

async function fetchFontCatalog(){if(fontCatalog.length)return fontCatalog;fontStatus.textContent="Loading Google Fonts catalog…";try{let r=await fetch("https://fonts.google.com/metadata/fonts");let text=await r.text();text=text.replace(/^\)\]\}'\s*/,"");let data=JSON.parse(text);fontCatalog=(data.familyMetadataList||[]).map(x=>x.family).sort();fontStatus.textContent=`${fontCatalog.length.toLocaleString()} fonts available.`}catch(e){fontCatalog=["IM Fell DW Pica","Cormorant Garamond","Playfair Display","DM Sans","Inter","Manrope","EB Garamond","Libre Baskerville","Caveat","Special Elite","Space Grotesk"];fontStatus.textContent="Using fallback font list. You can still type an exact Google Font name."}return fontCatalog}
async function searchFonts(q){q=q.trim().toLowerCase();if(!q){fontResults.innerHTML="";fontStatus.textContent="Type a font name to search.";return}let fonts=await fetchFontCatalog();let results=fonts.filter(f=>f.toLowerCase().includes(q)).slice(0,30);fontResults.innerHTML="";fontStatus.textContent=results.length?`${results.length} matching fonts.`:"No catalog match. You can try the exact family name.";results.forEach(name=>{let b=document.createElement("button");b.type="button";b.className="font-result";b.textContent=name;b.style.fontFamily=`"${name}", serif`;b.onclick=()=>selectFont(name);fontResults.appendChild(b)})}
function selectFont(name){state.settings.appearance.font=name;loadGoogleFont(name);fontSearch.value=name;fontPreview.style.fontFamily=`"${name}", serif`;fontResults.innerHTML="";fontStatus.textContent=`Selected: ${name}`}
fontSearch.addEventListener("input",()=>{clearTimeout(fontSearchTimer);fontSearchTimer=setTimeout(()=>searchFonts(fontSearch.value),250)});fontSearch.addEventListener("focus",()=>fetchFontCatalog());

saveSettings.onclick=()=>{state.settings.title=titleInput.value.trim()||"DAILY";habitEditor.querySelectorAll("input[data-id]").forEach(i=>{let h=state.settings.habits.find(x=>x.id===i.dataset.id);if(h)h.name=i.value.trim()||"Untitled habit"});state.settings.appearance.font=fontSearch.value.trim()||state.settings.appearance.font;state.settings.appearance.fontStyle=fontStyleInput.value;["fontSize","radius","cellRadius","gap"].forEach(k=>state.settings.appearance[k]=Number(document.getElementById(k+"Input").value));saveState();dialog.close();render()};
resetAppearance.onclick=()=>{state.settings.appearance={...defaultAppearance};renderSettings();applyAppearance()};resetCurrentWeek.onclick=()=>{if(confirm("Clear all completion data for this displayed week?")){delete state.weeks[getWeekKey()];saveState();dialog.close();render()}};

/* HSV / RGB / HEX COLOR PICKER */
function hexToRgb(hex){hex=hex.replace("#","");if(hex.length===3)hex=hex.split("").map(x=>x+x).join("");let n=parseInt(hex,16);return{r:(n>>16)&255,g:(n>>8)&255,b:n&255}}
function rgbToHex(r,g,b){return "#"+[r,g,b].map(x=>Math.max(0,Math.min(255,Math.round(x))).toString(16).padStart(2,"0")).join("")}
function rgbToHsv(r,g,b){r/=255;g/=255;b/=255;let max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min,h=0;if(d){if(max===r)h=60*(((g-b)/d)%6);else if(max===g)h=60*((b-r)/d+2);else h=60*((r-g)/d+4)}if(h<0)h+=360;return{h:Math.round(h),s:Math.round(max?d/max*100:0),v:Math.round(max*100)}}
function hsvToRgb(h,s,v){s/=100;v/=100;let c=v*s,x=c*(1-Math.abs((h/60)%2-1)),m=v-c,r=0,g=0,b=0;if(h<60)[r,g,b]=[c,x,0];else if(h<120)[r,g,b]=[x,c,0];else if(h<180)[r,g,b]=[0,c,x];else if(h<240)[r,g,b]=[0,x,c];else if(h<300)[r,g,b]=[x,0,c];else[r,g,b]=[c,0,x];return{r:Math.round((r+m)*255),g:Math.round((g+m)*255),b:Math.round((b+m)*255)}}
function hsvHex(){let {r,g,b}=hsvToRgb(pickerHSV.h,pickerHSV.s,pickerHSV.v);return rgbToHex(r,g,b)}
function updatePicker(){let hue=`hsl(${pickerHSV.h},100%,50%)`;colorSquare.style.background=`linear-gradient(to top,#000,transparent),linear-gradient(to right,#fff,${hue})`;colorSquareCursor.style.left=pickerHSV.s+"%";colorSquareCursor.style.top=(100-pickerHSV.v)+"%";let rgb=hsvToRgb(pickerHSV.h,pickerHSV.s,pickerHSV.v),hex=rgbToHex(rgb.r,rgb.g,rgb.b);colorPreview.style.background=hex;hInput.value=pickerHSV.h;sInput.value=pickerHSV.s;bInput.value=pickerHSV.v;rInput.value=rgb.r;gInput.value=rgb.g;bRgbInput.value=rgb.b;hexInput.value=hex}
function openColorPicker(key){activeColorKey=key;colorDialogTitle.textContent=`Choose ${key.replace(/([A-Z])/g," $1")}`;let rgb=hexToRgb(state.settings.appearance[key]);pickerHSV=rgbToHsv(rgb.r,rgb.g,rgb.b);updatePicker();colorDialog.showModal()}
function squarePosition(e){let rect=colorSquare.getBoundingClientRect();let x=Math.max(0,Math.min(rect.width,e.clientX-rect.left)),y=Math.max(0,Math.min(rect.height,e.clientY-rect.top));pickerHSV.s=Math.round(x/rect.width*100);pickerHSV.v=Math.round(100-y/rect.height*100);updatePicker()}
colorSquare.addEventListener("pointerdown",e=>{colorSquare.setPointerCapture(e.pointerId);squarePosition(e)});colorSquare.addEventListener("pointermove",e=>{if(e.buttons) squarePosition(e)});
hueSlider.oninput=e=>{pickerHSV.h=Number(e.target.value);updatePicker()};
[hInput,sInput,bInput].forEach((el,i)=>el.oninput=()=>{pickerHSV.h=Math.max(0,Math.min(360,Number(hInput.value)||0));pickerHSV.s=Math.max(0,Math.min(100,Number(sInput.value)||0));pickerHSV.v=Math.max(0,Math.min(100,Number(bInput.value)||0));hueSlider.value=pickerHSV.h;updatePicker()});
[rInput,gInput,bRgbInput].forEach(el=>el.oninput=()=>{let r=Number(rInput.value)||0,g=Number(gInput.value)||0,b=Number(bRgbInput.value)||0;pickerHSV=rgbToHsv(r,g,b);hueSlider.value=pickerHSV.h;updatePicker()});
hexInput.oninput=()=>{if(/^#?[0-9a-fA-F]{6}$/.test(hexInput.value)){let rgb=hexToRgb(hexInput.value);pickerHSV=rgbToHsv(rgb.r,rgb.g,rgb.b);hueSlider.value=pickerHSV.h;updatePicker()}};
closeColorPicker.onclick=()=>colorDialog.close();cancelColor.onclick=()=>colorDialog.close();applyColor.onclick=()=>{if(activeColorKey){state.settings.appearance[activeColorKey]=hsvHex();renderColorControls();colorDialog.close()}};
fontStyleInput.onchange=()=>{fontPreview.style.fontStyle=fontStyleInput.value};
render();